### ISSUE TITLE
Please update to crossterm 0.27.0

### ISSUE THREAD

**Issue by sylvestre** [iximeow/yaxpeax-arch#6]
the current version is a bit old - makes it harder to package it

**Comment by iximeow** [comment]
oh it sure is. i'll have to take a look at if i've accidentally exported items from crossterm to find out if bumping crossterm a major or minor version change for `yaxpeax-arch`. there are a few crates from this vintage that have that... unfortunate wrinkle. if it would be a major bump i'll also be curious about what can be done in a minor bump kinda way..

crossterm itself is an optional dependency for a relatively unused feature in the crate, so i'd be curious if a slightly tweaked cargo stanza might let you drop the dependency too. (or if it's a used feature, i'm definitely interested in how the crate is used there.) i think there are a few ways to end up using `yaxpeax-arch` in a way that you'd end up packaging, is it through `minidump-processor` or something else?

**Comment by iximeow** [comment]
done! https://github.com/iximeow/yaxpeax-arch/commit/1e9cf24e4ceca8bfd48ff3e6f777fcec54b9a186, published as yaxpeax-arch 0.2.8.

**Comment by sylvestre** [comment]
Many thanks
